on:
  push:
    tags:
      - 'v*.*.*'

name: Publish

jobs:
  test:
    name: Build and test
    runs-on: docker
    uses: ./.forgejo/workflows/ci.yaml

  publish:
    name: "Publish to crates.io"
    runs-on: docker
    needs: [test]
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ forgejo.event.pull_request.head.sha }}

      - uses: https://github.com/actions-rs/toolchain@v1
        name: Install toolchain
        with:
            toolchain: stable
            override: true

      - name: Publish to crates.io
        uses: https://github.com/actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: --locked --dry-run

      - name: Create release
        uses: https://code.forgejo.org/actions/forgejo-release@v2.11.1
        with:
          direction: "upload"
          release-notes-assistant: true
          skip-assets: true
